import React, { useState } from 'react'
import { Link } from 'react-router-dom'
import { useCart } from '../context/CartContext.jsx'

export default function Cart() {
  const { items, removeFromCart, updateQty, clearCart, totalPrice } = useCart()
  const [error, setError] = useState('')
  const shipping = items.length ? 40 : 0
  const changeQty = async (id, qty) => { try { setError(''); await updateQty(id, qty) } catch (e) { setError(e.message?.startsWith('ONLY_') ? `المتاح من المنتج ${e.message.slice(5)} فقط` : 'تعذر تحديث الكمية') } }
  if (!items.length) return <div className="container py-5 text-center"><i className="bi bi-basket3" style={{fontSize:'3rem',color:'var(--coffee-700)'}}></i><h1 className="section-title h3 mt-3">السلة فاضية</h1><p className="mb-4" style={{color:'var(--coffee-700)'}}>لسه ما اخترتش رحلة بن... يلا نشوف المتجر</p><Link to="/products" className="btn-brew">تصفح المتجر</Link></div>
  return <div className="container py-5"><div className="d-flex justify-content-between align-items-center mb-4 flex-wrap gap-2"><h1 className="section-title h2 mb-0">سلة المشتريات</h1><button className="btn btn-sm" onClick={clearCart}>إفراغ السلة</button></div>{error&&<p style={{color:'var(--stamp-red)'}}>{error}</p>}<div className="row g-5"><div className="col-lg-8">{items.map(item=><div className="cart-row py-3 d-flex align-items-center gap-3 flex-wrap" key={item.id}><img src={item.image} alt={item.name} style={{width:80,height:80,objectFit:'cover',borderRadius:4}}/><div className="flex-grow-1"><h3 className="h6 mb-1">{item.name}</h3><p className="small mb-0" style={{color:'var(--coffee-700)'}}>{item.country} — {item.unit}</p><small style={{color:'var(--coffee-700)'}}>متاح: {item.stock}</small></div><div className="d-flex align-items-center" style={{border:'1px solid var(--cream-line)',borderRadius:3}}><button className="btn btn-sm" onClick={()=>changeQty(item.id,item.qty-1)}>−</button><span className="px-2">{item.qty}</span><button className="btn btn-sm" onClick={()=>changeQty(item.id,item.qty+1)}>+</button></div><strong style={{minWidth:90,textAlign:'left'}}>{item.qty*item.price} ج.م</strong><button className="btn btn-sm text-danger" onClick={()=>removeFromCart(item.id)}><i className="bi bi-trash"></i></button></div>)}</div><div className="col-lg-4"><div className="origin-card p-4"><h2 className="h5 mb-3">ملخص الطلب</h2><div className="d-flex justify-content-between mb-2"><span>المنتجات</span><span>{totalPrice} ج.م</span></div><div className="d-flex justify-content-between mb-3"><span>الشحن</span><span>{shipping} ج.م</span></div><hr/><div className="d-flex justify-content-between mb-4 fw-bold fs-5"><span>الإجمالي</span><span>{totalPrice+shipping} ج.م</span></div><Link to="/checkout" className="btn-brew w-100 d-block text-center">إتمام الطلب</Link></div></div></div></div>
}
