import React, { useEffect, useState } from 'react'
const API_URL='http://localhost:3001'
export default function AdminCategories(){
 const [items,setItems]=useState([]),[form,setForm]=useState({name:'',description:''}),[editingId,setEditingId]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const load=async()=>{setLoading(true);try{const r=await fetch(`${API_URL}/categories?_sort=name`);setItems(await r.json())}catch{setError('مش قادر أجيب التصنيفات')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const submit=async(e)=>{e.preventDefault();setSaving(true);try{const body={name:form.name.trim(),description:form.description.trim(),active:true};if(editingId)await fetch(`${API_URL}/categories/${editingId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});else await fetch(`${API_URL}/categories`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setForm({name:'',description:''});setEditingId(null);await load()}catch{setError('حصل خطأ أثناء الحفظ')}finally{setSaving(false)}}
 const remove=async(id)=>{if(!window.confirm('حذف التصنيف؟'))return;const used=await fetch(`${API_URL}/products?categoryId=${id}`).then(r=>r.json());if(used.length){alert('مينفعش تحذف تصنيف عليه منتجات. غيّر تصنيف المنتجات الأول.');return}await fetch(`${API_URL}/categories/${id}`,{method:'DELETE'});setItems(x=>x.filter(i=>i.id!==id))}
 return <div><div className="origin-card p-4 mb-4"><h2 className="h5 mb-3">{editingId?'تعديل التصنيف':'إضافة تصنيف'}</h2><form onSubmit={submit} className="d-flex flex-column gap-3"><input required className="form-control form-control-beanroute" placeholder="اسم التصنيف" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><textarea className="form-control form-control-beanroute" rows="2" placeholder="وصف التصنيف" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="d-flex gap-2"><button disabled={saving} className="btn-brew">{saving?'جاري الحفظ...':editingId?'حفظ':'إضافة'}</button>{editingId&&<button type="button" className="btn-brew-outline" onClick={()=>{setEditingId(null);setForm({name:'',description:''})}}>إلغاء</button>}</div></form>{error&&<p className="mt-3 mb-0" style={{color:'var(--stamp-red)'}}>{error}</p>}</div>{loading?<p>جاري التحميل...</p>:<div className="d-flex flex-column gap-3">{items.map(c=><div className="origin-card p-3 d-flex align-items-center gap-3" key={c.id}><div className="flex-grow-1"><strong>{c.name}</strong><p className="small mb-0" style={{color:'var(--coffee-700)'}}>{c.description}</p></div><button className="btn btn-sm" onClick={()=>{setEditingId(c.id);setForm({name:c.name,description:c.description||''})}}>تعديل</button><button className="btn btn-sm" onClick={()=>remove(c.id)} style={{color:'var(--stamp-red)'}}>حذف</button></div>)}</div>}</div>
}
